export const mockDataTeam = [
    {
      id: 1,
      name: "Hán Hiến Đế",
      email: "FullStack React",
      age: 35,
      phone: "9324758",
      access: "pending",
    },
    {
      id: 2,
      name: "Minh Hồng Vũ",
      email: "Lập trình OOP",
      age: 42,
      phone: "3463",
      access: "confirmed",
    },
    {
      id: 3,
      name: "Tần Thủy Hoàng",
      email: "Đốt Sách Chôn Nho",
      age: 45,
      phone: "543534",
      access: "cancelled",
    },
    {
      id: 4,
      name: "Minh Thái Tông",
      email: "Đại Vận Hà",
      age: 16,
      phone: "2345",
      access: "pending",
    },
    {
      id: 5,
      name: "Nguyễn Trung Trực",
      email: "Bình Tây Đại Nguyên Soái",
      age: 31,
      phone: "456546",
      access: "pending",
    },
    {
      id: 6,
      name: "Ever Melisandre",
      email: "Kỹ Thuật Thâu Tóm Thiên Hạ",
      age: 150,
      phone: "086767",
      access: "pending",
    },
    {
      id: 7,
      name: "Ferrara Clifford",
      email: "Chữ Người Tử Tồ",
      age: 44,
      phone: "53434",
      access: "pending",
    },
    {
      id: 8,
      name: "Rossini Frances",
      email: "React and Mongodb",
      age: 36,
      phone: "4566",
      access: "pending",
    },
    {
      id: 9,
      name: "Lý Thế Dân",
      email: "Vạn Lý Trường Thành",
      age: 65,
      phone: "4565",
      access: "pending",
    },
    {
      id: 10,
      name: "Alexander Đại Đế",
      email: "Chinh Phục Thế Giới",
      age: 32,
      phone: "784562",
      access: "confirmed",
    },
    {
      id: 11,
      name: "Triệu Vân",
      email: "Thường Sơn Triệu Tử Long",
      age: 40,
      phone: "555666",
      access: "pending",
    },
    {
      id: 12,
      name: "Lưu Bị",
      email: "Tam Quốc Diễn Nghĩa",
      age: 61,
      phone: "123456",
      access: "cancelled",
    },
    {
      id: 13,
      name: "Quan Vũ",
      email: "Hổ Lao Quan",
      age: 39,
      phone: "987654",
      access: "confirmed",
    },
    {
      id: 14,
      name: "Trần Hưng Đạo",
      email: "Hịch Tướng Sĩ",
      age: 50,
      phone: "098123",
      access: "pending",
    },
    {
      id: 15,
      name: "Napoleon Bonaparte",
      email: "Chiến Lược Quân Sự",
      age: 52,
      phone: "876543",
      access: "confirmed",
    },
    {
      id: 16,
      name: "Julius Caesar",
      email: "La Mã Cổ Đại",
      age: 55,
      phone: "555777",
      access: "pending",
    },
    {
      id: 17,
      name: "Mạc Đăng Dung",
      email: "Võ Sĩ Trạng Nguyên",
      age: 34,
      phone: "443322",
      access: "pending",
    },
    {
      id: 18,
      name: "Đặng Tiểu Bình",
      email: "Cải Cách Kinh Tế",
      age: 79,
      phone: "334455",
      access: "cancelled",
    },
    {
      id: 19,
      name: "Lê Lợi",
      email: "Bình Ngô Đại Cáo",
      age: 48,
      phone: "223344",
      access: "confirmed",
    },
    {
      id: 20,
      name: "Trần Quốc Toản",
      email: "Phá Giặc Ngoại Xâm",
      age: 15,
      phone: "778899",
      access: "pending",
    },
    {
      id: 21,
      name: "Võ Nguyên Giáp",
      email: "Chiến Thắng Điện Biên",
      age: 92,
      phone: "667788",
      access: "confirmed",
    },
    {
      id: 22,
      name: "Hồ Chí Minh",
      email: "Cách Mạng Việt Nam",
      age: 79,
      phone: "990088",
      access: "confirmed",
    },
    {
      id: 23,
      name: "Lý Công Uẩn",
      email: "Dời Đô Thăng Long",
      age: 50,
      phone: "550011",
      access: "pending",
    },
    {
      id: 24,
      name: "Phạm Ngũ Lão",
      email: "Tướng Lĩnh Thời Trần",
      age: 40,
      phone: "443300",
      access: "pending",
    },
    {
      id: 25,
      name: "Đức Thánh Trần",
      email: "Tấm Gương Tướng Lĩnh",
      age: 60,
      phone: "009988",
      access: "pending",
    },
    {
      id: 26,
      name: "Nguyễn Huệ",
      email: "Quang Trung Đại Đế",
      age: 40,
      phone: "334400",
      access: "cancelled",
    },
    {
      id: 27,
      name: "Ngô Quyền",
      email: "Chiến Thắng Bạch Đằng",
      age: 47,
      phone: "778800",
      access: "pending",
    },
    {
      id: 28,
      name: "Trần Nhân Tông",
      email: "Phật Hoàng",
      age: 55,
      phone: "998877",
      access: "confirmed",
    },
    {
      id: 29,
      name: "Thái Bình Công Chúa",
      email: "Nữ Tướng Nhà Đường",
      age: 60,
      phone: "665544",
      access: "pending",
    },
    {
      id: 30,
      name: "Khổng Minh",
      email: "Gia Cát Lượng",
      age: 54,
      phone: "889900",
      access: "pending",
    },
  ];
  